# Define local configurations. DO NOT push the local configuration                                                       |1149                 } else {                                                                                            |255 struct nvmev_dev {
#KERNELDIR := /path/to/other/kernel/source
